# -*- coding: utf-8 -*-
"""webcam_download.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GveohYNS8MmfH7EbXjzq2ciLkF5MVqFo
"""

import requests
import os
from bs4 import BeautifulSoup
from datetime import datetime, date, timedelta

folder_path = "webcam_MI_2026"
os.makedirs(folder_path, exist_ok=True)

def save_images_giugliacci(image_sources, base_url, folder_name):
    current_date = date.today() - timedelta(days=1)
    save_folder = folder_path
    os.makedirs(save_folder, exist_ok=True)

    for source in image_sources:
        url = base_url + source if base_url else source
        response = requests.get(url, headers={"User-Agent": "Mozilla/5.0"})

        if response.status_code == 200:

            filename = os.path.basename(source)

            hour_str = "0000"
            hour_match = filename.lower().split("hour")

            if len(hour_match) > 1 and hour_match[1][:2].isdigit():
                hour_str = f"{int(hour_match[1][:2]):02d}00"

            filename = f"{current_date.strftime('%Y%m%d')}-{hour_str}.jpg"

            filepath = os.path.join(save_folder, filename)

            with open(filepath, 'wb') as f:
                f.write(response.content)

            print("Saved:", filepath)


URL = "https://www.meteogiuliacci.it/meteo-webcam/webcam-milano"

r = requests.get(URL, headers={"User-Agent": "Mozilla/5.0"})
soup = BeautifulSoup(r.text, "html.parser")

images = soup.find_all("img")

imageSources = [
    img.get("src")
    for img in images
    if img.get("src")
    and img.get("src").endswith((".png", ".jpg", ".jpeg"))
    and "hour" in img.get("src")
]

save_images_giugliacci(imageSources, None, "giuliacci")
